spring.application.name=ColegioService

# Conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/colegio_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
